//Product Management
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_METAL = "GET_METAL";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_METAL = "ADD_METAL";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_METAL = "UPDATE_METAL";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_METAL = "DELETE_METAL";
export const RESET_GLOBAL_STATE = "RESET_GLOBAL_STATE";
export const GET_PRODUCT = "GET_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const GET_ORDER_LIST = "GET_ORDER_LIST";
export const GET_ORDER_BY_ID = "GET_ORDER_BY_ID";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const GET_GROUP_ITEM = "GET_GROUP_ITEM";
export const DELETE_GROUP_ITEM = "DELETE_GROUP_ITEM";
export const UPDATE_GROUP_ITEM = "UPDATE_GROUP_ITEM";
export const ADD_GROUP_ITEM = "ADD_GROUP_ITEM";
export const GET_NON_BARCODE_CATEGORY = "GET_NON_BARCODE_CATEGORY";
export const ADD_NON_BARCODE_CATEGORY = "ADD_NON_BARCODE_CATEGORY";
export const UPDATE_NON_BARCODE_CATEGORY = "UPDATE_NON_BARCODE_CATEGORY";
export const DELETE_NON_BARCODE_CATEGORY= "DELETE_NON_BARCODE_CATEGORY";
export const DELETE_NON_BARCODE_PRODUCT ="DELETE_NON_BARCODE_PRODUCT";
export const ADD_NON_BARCODE_PRODUCT = "ADD_NON_BARCODE_PRODUCT";
export const GET_NON_BARCODE_PRODUCT = "GET_NON_BARCODE_PRODUCT";
export const DELETE_SIZE ="DELETE_SIZE";
export const DELETE_DESIGN = "DELETE_DESIGN";
export const UPDATE_SIZE = "UPDATE_SIZE";
export const UPDATE_DESIGN = "UPDATE_DESIGN";
export const ADD_SIZE = "ADD_SIZE";
export const ADD_DESIGN = "ADD_DESIGN";
export const GET_SIZE = "GET_SIZE";
export const GET_DESIGN = "GET_DESIGN";


//General Management
export const GET_PERCENTAGE = "GET_PERCENTAGE";
export const GET_UCHAK = "GET_UCHAK";
export const GET_TAG = "GET_TAG";
export const GET_MARKET_RATE = "GET_MARKET_RATE";
export const GET_BRAND = "GET_BRAND";
export const GET_PERGRAM = "GET_PERGRAM";
export const ADD_PERCENTAGE = "ADD_PERCENTAGE";
export const ADD_UCHAK = "ADD_UCHAK";
export const ADD_TAG = "ADD_TAG";
export const ADD_MARKET_RATE = "ADD_MARKET_RATE";
export const ADD_COMPANY_INFO = "ADD_COMPANY_INFO";
export const ADD_PERGRAM = "ADD_PERGRAM";
export const UPDATE_PERCENTAGE = "UPDATE_PERCENTAGE";
export const UPDATE_UCHAK = "UPDATE_UCHAK";
export const UPDATE_TAG = "UPDATE_TAG";
export const UPDATE_ATTRIBUTE =  "UPDATE_ATTRIBUTE";
export const UPDATE_BRAND = "UPDATE_BRAND";
export const UPDATE_PERGRAM = "UPDATE_PERGRAM";
export const DELETE_PERCENTAGE = "DELETE_PERCENTAGE";
export const DELETE_UCHAK = "DELETE_UCHAK";
export const DELETE_TAG = "DELETE_TAG";
export const DELETE_ATTRIBUTE = "DELETE_ATTRIBUTE";
export const DELETE_BRAND = "DELETE_BRAND";
export const DELETE_PERGRAM = "DELETE_PERGRAM";
export const GET_BILL_BY_ID = "GET_BILL_BY_ID";


//User Management

export const GET_USERS = "GET_USERS";
export const ADD_ABOUT_US = "ADD_ABOUT_US";
export const GET_CONTACT_US = "GET_CONTACT_US";
export const LOGIN_ADMIN = "LOGIN_ADMIN";
export const UPDATE_USER = "UPDATE_USER";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const GET_COMPANY_INFO = "GET_COMPANY_INFO";

//Support Management
export const GET_WARRANTIES = "GET_WARRANTIES";
export const GET_COMPLAINTS = "GET_COMPLAINTS";
export const DELETE_COMPLAINT ="DELETE_COMPLAINT";
export const GET_ISSUES = "GET_ISSUES";
export const GET_QUICK_FIX = "GET_QUICK_FIX";
export const DELETE_ISSUE = "DELETE_ISSUE";
export const EDIT_ISSUE = "EDIT_ISSUE";
export const ADD_ISSUE = "ADD_ISSUE";
export const ADD_QUICKFIX = "ADD_QUICKFIX";
export const EDIT_QUICKFIX = "EDIT_QUICKFIX";
export const DELETE_QUICKFIX = "DELETE_QUICKFIX";