//Product Management
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_METAL = "GET_METAL";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_METAL = "ADD_METAL";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_METAL = "UPDATE_METAL";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_METAL = "DELETE_METAL";
export const RESET_GLOBAL_STATE = "RESET_GLOBAL_STATE";
export const GET_PRODUCT = "GET_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const GET_ORDER_LIST = "GET_ORDER_LIST";
export const GET_ORDER_BY_ID = "GET_ORDER_BY_ID";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const GET_GROUP_ITEM = "GET_GROUP_ITEM";
export const DELETE_GROUP_ITEM = "DELETE_GROUP_ITEM";
export const UPDATE_GROUP_ITEM = "UPDATE_GROUP_ITEM";
export const ADD_GROUP_ITEM = "ADD_GROUP_ITEM";


//General Management
export const GET_PRODUCT_COLLECTION = "GET_PRODUCT_COLLECTION";
export const GET_PRODUCT_STATUS = "GET_PRODUCT_STATUS";
export const GET_TAG = "GET_TAG";
export const GET_ATTRIBUTE = "GET_ATTRIBUTE";
export const GET_BRAND = "GET_BRAND";
export const GET_LABEL = "GET_LABEL";
export const ADD_PRODUCT_COLLECTION = "ADD_PRODUCT_COLLECTION";
export const ADD_PRODUCT_STATUS = "ADD_PRODUCT_STATUS";
export const ADD_TAG = "ADD_TAG";
export const ADD_ATTRIBUTE = "ADD_ATTRIBUTE";
export const ADD_COMPANY_INFO = "ADD_COMPANY_INFO";
export const ADD_LABEL = "ADD_LABEL";
export const UPDATE_PRODUCT_COLLECTION = "UPDATE_PRODUCT_COLLECTION";
export const UPDATE_PRODUCT_STATUS = "UPDATE_PRODUCT_STATUS";
export const UPDATE_TAG = "UPDATE_TAG";
export const UPDATE_ATTRIBUTE =  "UPDATE_ATTRIBUTE";
export const UPDATE_BRAND = "UPDATE_BRAND";
export const UPDATE_LABEL = "UPDATE_LABEL";
export const DELETE_PRODUCT_COLLECTION = "DELETE_PRODUCT_COLLECTION";
export const DELETE_PRODUCT_STATUS = "DELETE_PRODUCT_STATUS";
export const DELETE_TAG = "DELETE_TAG";
export const DELETE_ATTRIBUTE = "DELETE_ATTRIBUTE";
export const DELETE_BRAND = "DELETE_BRAND";
export const DELETE_LABEL = "DELETE_LABEL";


//User Management

export const GET_USERS = "GET_USERS";
export const ADD_ABOUT_US = "ADD_ABOUT_US";
export const GET_CONTACT_US = "GET_CONTACT_US";
export const LOGIN_ADMIN = "LOGIN_ADMIN";
export const UPDATE_USER = "UPDATE_USER";
export const GET_USER_BY_ID = "GET_USER_BY_ID";

//Support Management
export const GET_WARRANTIES = "GET_WARRANTIES";
export const GET_COMPLAINTS = "GET_COMPLAINTS";
export const DELETE_COMPLAINT ="DELETE_COMPLAINT";
export const GET_ISSUES = "GET_ISSUES";
export const GET_QUICK_FIX = "GET_QUICK_FIX";
export const DELETE_ISSUE = "DELETE_ISSUE";
export const EDIT_ISSUE = "EDIT_ISSUE";
export const ADD_ISSUE = "ADD_ISSUE";
export const ADD_QUICKFIX = "ADD_QUICKFIX";
export const EDIT_QUICKFIX = "EDIT_QUICKFIX";
export const DELETE_QUICKFIX = "DELETE_QUICKFIX";